---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: $SERVICE_NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        command: [/bin/sh]
        args:
        - -c
        - >
          apk add --update restic==$VERSION_RESTIC tzdata &&
          ln -s /usr/share/zoneinfo/${DOL}TZ /etc/localtime &&
          echo $TZ > /etc/timezone &&
          echo "if [ -r ${DOL}HOME/.resticrc ]; then . ${DOL}HOME/.resticrc; fi" \
            >>/etc/profile.d/restic.sh &&
          touch /var/log/restic.log && /usr/sbin/crond &&
          mkdir -p /var/log/week && tail -f -n 0 /var/log/restic.log
        env:
        - { name: ENV, value: /etc/profile }
        - { name: TZ, value: $TZ }
        image: alpine:3.12
        resources:
          limits:
            memory: 2048Mi
          requests:
            cpu: 200m
            memory: 512Mi
        volumeMounts:
        - mountPath: /var/spool/cron/crontabs/root
          name: config
          subPath: cron
        - mountPath: /root/.restic/excludes.txt
          name: config
          subPath: excludes.txt
        - mountPath: /root/.resticrc
          name: config
          subPath: .resticrc
        - mountPath: /bin/set-key.sh
          name: config
          subPath: set-key.sh
        - mountPath: /root/.cache/restic
          name: cache

        # this secret should contain keys b2-account-id / b2-account-key
        # and any other API id/key pairs
        - mountPath: /root/.restic/b2-apikey
          name: b2-apikey

        # this secret has keys restic-repo-local (for rest-server) and
        # restic-repo-password (default encryption key for all repos)
        - mountPath: /root/.restic/repo-password
          name: restic-repo-password

        - mountPath: /var/log
          name: logs
        - mountPath: /restore
          name: restore
        - mountPath: /b/share
          name: share

        # list of volumes to back up, customize as needed
        - mountPath: /b/services
          name: backup
          readOnly: true
        - mountPath: /b/cloud
          name: cloud
          readOnly: true
        - mountPath: /b/samba_dos
          name: dos
          readOnly: true
        - mountPath: /b/ftp
          name: ftp
          readOnly: true
        - mountPath: /b/gitlab
          name: gitlab
          readOnly: true
        - mountPath: /b/home
          name: home
          readOnly: true
        - mountPath: /b/household
          name: household
          readOnly: true
        - mountPath: /b/inbox
          name: inbox
          readOnly: true
        - mountPath: /b/jira
          name: jira
          readOnly: true
        - mountPath: /b/pc/MP3
          name: mp3
          readOnly: true
        - mountPath: /b/nexus
          name: nexus
          readOnly: true
        - mountPath: /b/share/ox-appsuite
          name: ox-appsuite
          readOnly: true
        - mountPath: /b/pc/Pictures
          name: pictures
          readOnly: true
        - mountPath: /b/share/rainloop
          name: rainloop
          readOnly: true
        - mountPath: /b/u
          name: user
          readOnly: true
        - mountPath: /b/webmail
          name: webmail
          readOnly: true
      imagePullSecrets: [ $IMAGEPULL_SPEC ]
      nodeSelector:
        service.data-sync: allow
      volumes:
      - name: config
        configMap:
          name: $SERVICE_NAME
      - name: b2-apikey
        secret:
          secretName: restic-b2-apikey
          defaultMode: 0400
      - name: restic-repo-password
        secret:
          secretName: restic-repo-password
          defaultMode: 0400
      - name: backup
        hostPath: { path: $PATH_BKP }
      - name: cache
        persistentVolumeClaim:
          claimName: restic-cache
      - name: logs
        hostPath: { path: $PATH_SHR/$SERVICE_NAME/logs }
      - name: restore
        persistentVolumeClaim:
          claimName: backup-restore

      # Volumes to be backed up
      - name: cloud
        hostPath: { path: $K8S_VOLUMES_PATH/cloud }
      - name: dos
        hostPath: { path: $K8S_VOLUMES_PATH/dos }
      - name: ftp
        persistentVolumeClaim:
          claimName: ftp
      - name: gitlab
        hostPath: { path: $K8S_VOLUMES_PATH/gitlab }
      - name: home
        hostPath: { path: $K8S_VOLUMES_PATH/home }
      - name: household
        hostPath: { path: $K8S_VOLUMES_PATH/household }
      - name: inbox
        hostPath: { path: $K8S_VOLUMES_PATH/inbox }
      - name: jira
        hostPath: { path: $K8S_VOLUMES_PATH/jira }
      - name: mp3
        persistentVolumeClaim:
          claimName: mp3
      - name: nexus
        hostPath: { path: $K8S_VOLUMES_PATH/nexus }
      - name: ox-appsuite
        hostPath: { path: $K8S_VOLUMES_PATH/share/ox-appsuite }
      - name: pictures
        persistentVolumeClaim:
          claimName: pictures
      - name: rainloop
        hostPath: { path: $K8S_VOLUMES_PATH/share/rainloop }
      - name: share
        hostPath: { path: $PATH_SHR }
      - name: user
        persistentVolumeClaim:
          claimName: user
      - name: webmail
        hostPath: { path: $K8S_VOLUMES_PATH/webmail }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: $SERVICE_NAME
data:
  .resticrc: |
    export B2_ACCOUNT_ID=`cat ${DOL}HOME/.restic/b2-apikey/b2-account-id`
    export B2_ACCOUNT_KEY=`cat ${DOL}HOME/.restic/b2-apikey/b2-account-key`
    export REPO_LOCAL_PASSWORD=`cat ${DOL}HOME/.restic/repo-password/restic-repo-local`
    export RESTIC_PASSWORD_FILE=${DOL}HOME/.restic/repo-password/restic-repo-password
    export BACKUP_OPTS="--exclude-file=${DOL}HOME/.restic/excludes.txt --host=k8s --json"
    export REPO_B2=b2:$RESTIC_BUCKET_NAME
    export REPO_B2_MAIL=b2:$RESTIC_BUCKET_MAIL
    export REPO_B2_PIC=b2:$RESTIC_BUCKET_PIC
    export REPO_B2_USER=b2:$RESTIC_BUCKET_USER
    export REPO_LOCAL=rest:http://bkp:${DOL}REPO_LOCAL_PASSWORD@$NFS_HOST_2:8000
    export RESTIC_PROGRESS_FPS=1
    export RETAIN_SCHED="forget --keep-daily 7 --keep-weekly 5 --keep-monthly 12 --keep-yearly 75"

  cron: |
    # Customize as desired
    # Here's a minimal example that does backups, retention, check and prune:
    #  0 2 * * * . /etc/profile && restic -r ${DOL}REPO_B2:b backup ${DOL}BACKUP_OPTS -x /b/home  | grep -v percent_done >>/var/log/restic.log && touch /var/log/b2-home-status.txt
    #  0 1 * * * . /etc/profile && restic -r ${DOL}REPO_B2:b ${DOL}RETAIN_SCHED >>/var/log/restic.log
    #  0 5 * * 0 . /etc/profile && restic -r ${DOL}REPO_B2:b check --verbose >>/var/log/restic.log
    #  0 5 2 * * . /etc/profile && restic -r ${DOL}REPO_B2:b prune >>/var/log/restic.log

    # This is a full-length example used by the author
    # Lower-frequency backups - twice a week
    45 1 * * 2,6 . /etc/profile && restic -r ${DOL}REPO_B2:misc backup ${DOL}BACKUP_OPTS -x /b/samba_dos /b/ftp /b/ftp/depot/Microsoft/ISO /b/ftp/depot/TechNet /b/jira/home/data /b/jira/home/plugins /b/pc/MP3 /b/services/gitlab /b/share/rainloop | grep -v percent_done >>/var/log/restic.log && touch /var/log/week/b2-misc-status.txt
    30 1 * * 1,5 . /etc/profile && restic -r ${DOL}REPO_LOCAL/misc backup ${DOL}BACKUP_OPTS -x /b/samba_dos /b/ftp /b/ftp/depot/Microsoft/ISO /b/ftp/depot/TechNet /b/jira /b/pc/MP3 /b/services/gitlab /b/share/rainloop | grep -v percent_done >>/var/log/restic.log && touch /var/log/week/local-misc-status.txt
    # Before doing the next backup, apply the defined retention schedule
    0 1 * * 2,6 . /etc/profile && restic -r ${DOL}REPO_B2:misc ${DOL}RETAIN_SCHED >>/var/log/restic.log
    0 1 * * 1,5 . /etc/profile && restic -r ${DOL}REPO_LOCAL/misc ${DOL}RETAIN_SCHED >>/var/log/restic.log

    # Daily savesets
    0 2 * * * . /etc/profile && restic -r ${DOL}REPO_B2:cloud backup ${DOL}BACKUP_OPTS -x /b/cloud | grep -v percent_done >>/var/log/restic.log && touch /var/log/b2-cloud-status.txt
    0 4 * * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/cloud backup ${DOL}BACKUP_OPTS -x /b/cloud | grep -v percent_done >>/var/log/restic.log && touch /var/log/local-cloud-status.txt
    5 1 * * * . /etc/profile && restic -r ${DOL}REPO_B2:cloud ${DOL}RETAIN_SCHED >>/var/log/restic.log
    5 1 * * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/cloud ${DOL}RETAIN_SCHED >>/var/log/restic.log

    20 2 * * * . /etc/profile && restic -r ${DOL}REPO_B2:household backup ${DOL}BACKUP_OPTS -x /b/household | grep -v percent_done >>/var/log/restic.log && touch /var/log/b2-household-status.txt
    20 4 * * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/household backup ${DOL}BACKUP_OPTS -x /b/household | grep -v percent_done >>/var/log/restic.log && touch /var/log/local-household-status.txt
    10 1 * * * . /etc/profile && restic -r ${DOL}REPO_B2:household ${DOL}RETAIN_SCHED >>/var/log/restic.log
    10 1 * * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/household ${DOL}RETAIN_SCHED >>/var/log/restic.log

    25 2 * * * . /etc/profile && restic -r ${DOL}REPO_B2:home backup ${DOL}BACKUP_OPTS -x /b/home | grep -v percent_done >>/var/log/restic.log && touch /var/log/b2-home-status.txt
    25 4 * * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/home backup ${DOL}BACKUP_OPTS -x /b/home | grep -v percent_done >>/var/log/restic.log && touch /var/log/local-home-status.txt
    12 1 * * * . /etc/profile && restic -r ${DOL}REPO_B2:home ${DOL}RETAIN_SCHED >>/var/log/restic.log
    12 1 * * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/home ${DOL}RETAIN_SCHED >>/var/log/restic.log

    30 2 * * * . /etc/profile && restic -r ${DOL}REPO_B2:nexus backup ${DOL}BACKUP_OPTS -x /b/nexus | grep -v percent_done >>/var/log/restic.log && touch /var/log/b2-nexus-status.txt
    30 4 * * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/nexus backup ${DOL}BACKUP_OPTS -x /b/nexus | grep -v percent_done >>/var/log/restic.log && touch /var/log/local-nexus-status.txt
    15 1 * * * . /etc/profile && restic -r ${DOL}REPO_B2:nexus ${DOL}RETAIN_SCHED >>/var/log/restic.log
    15 1 * * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/nexus ${DOL}RETAIN_SCHED >>/var/log/restic.log

    40 2 * * * . /etc/profile && . /bin/set-key.sh pictures && restic -r ${DOL}REPO_B2_PIC:pictures backup ${DOL}BACKUP_OPTS /b/pc/Pictures | grep -v percent_done >>/var/log/restic.log && touch /var/log/b2-pictures-status.txt
    40 4 * * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/pictures backup ${DOL}BACKUP_OPTS /b/pc/Pictures | grep -v percent_done >>/var/log/restic.log && touch /var/log/local-pictures-status.txt
    20 1 * * * . /etc/profile && . /bin/set-key.sh pictures && restic -r ${DOL}REPO_B2_PIC:pictures ${DOL}RETAIN_SCHED >>/var/log/restic.log
    20 1 * * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/pictures ${DOL}RETAIN_SCHED >>/var/log/restic.log

    0 3 * * * . /etc/profile && restic -r ${DOL}REPO_B2:share backup ${DOL}BACKUP_OPTS -x /b/share | grep -v percent_done >>/var/log/restic.log && touch /var/log/b2-share-status.txt
    0 5 * * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/share backup ${DOL}BACKUP_OPTS -x /b/share | grep -v percent_done >>/var/log/restic.log && touch /var/log/local-share-status.txt
    25 1 * * * . /etc/profile && restic -r ${DOL}REPO_B2:share ${DOL}RETAIN_SCHED >>/var/log/restic.log
    25 1 * * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/share ${DOL}RETAIN_SCHED >>/var/log/restic.log

    10 3 * * * . /etc/profile && . /bin/set-key.sh user && restic -r ${DOL}REPO_B2_USER:u backup ${DOL}BACKUP_OPTS -x /b/u | grep -v percent_done >>/var/log/restic.log && touch /var/log/b2-u-status.txt
    10 5 * * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/u backup ${DOL}BACKUP_OPTS -x /b/u | grep -v percent_done >>/var/log/restic.log && touch /var/log/local-u-status.txt
    30 1 * * * . /etc/profile && . /bin/set-key.sh user && restic -r ${DOL}REPO_B2_USER:u ${DOL}RETAIN_SCHED >>/var/log/restic.log
    30 1 * * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/u ${DOL}RETAIN_SCHED >>/var/log/restic.log

    30 3 * * * . /etc/profile && . /bin/set-key.sh mail && restic -r ${DOL}REPO_B2_MAIL:webmail backup ${DOL}BACKUP_OPTS -x /b/inbox /b/webmail | grep -v percent_done >>/var/log/restic.log && touch /var/log/b2-webmail-status.txt
    30 5,13,21 * * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/webmail backup ${DOL}BACKUP_OPTS -x /b/inbox /b/webmail | grep -v percent_done >>/var/log/restic.log && touch /var/log/local-webmail-status.txt
    35 1 * * * . /etc/profile && . /bin/set-key.sh mail && restic -r ${DOL}REPO_B2_MAIL:webmail ${DOL}RETAIN_SCHED >>/var/log/restic.log
    35 1 * * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/webmail ${DOL}RETAIN_SCHED --keep-hourly=3 >>/var/log/restic.log

    # Check weekly, on Sun/Mon
    0 5 * * 0 . /etc/profile && restic -r ${DOL}REPO_B2:misc check --verbose >>/var/log/restic.log
    5 5 * * 0 . /etc/profile && restic -r ${DOL}REPO_B2:cloud check --verbose >>/var/log/restic.log
    10 5 * * 0 . /etc/profile && restic -r ${DOL}REPO_B2:household check --verbose >>/var/log/restic.log
    15 5 * * 0 . /etc/profile && restic -r ${DOL}REPO_B2:nexus check --verbose >>/var/log/restic.log
    20 5 * * 0 . /etc/profile && . /bin/set-key.sh pictures && restic -r ${DOL}REPO_B2_PIC:pictures check --verbose >>/var/log/restic.log
    25 5 * * 0 . /etc/profile && restic -r ${DOL}REPO_B2:share check --verbose >>/var/log/restic.log
    30 5 * * 0 . /etc/profile && . /bin/set-key.sh user && restic -r ${DOL}REPO_B2_USER:u check --verbose >>/var/log/restic.log
    35 5 * * 0 . /etc/profile && . /bin/set-key.sh mail && restic -r ${DOL}REPO_B2_MAIL:webmail check --verbose >>/var/log/restic.log
    40 5 * * 0 . /etc/profile && restic -r ${DOL}REPO_B2:home check --verbose >>/var/log/restic.log
    0 5 * * 1 . /etc/profile && restic -r ${DOL}REPO_LOCAL/misc check --verbose >>/var/log/restic.log
    5 5 * * 1 . /etc/profile && restic -r ${DOL}REPO_LOCAL/cloud check --verbose >>/var/log/restic.log
    10 5 * * 1 . /etc/profile && restic -r ${DOL}REPO_LOCAL/household check --verbose >>/var/log/restic.log
    15 5 * * 1 . /etc/profile && restic -r ${DOL}REPO_LOCAL/nexus check --verbose >>/var/log/restic.log
    20 5 * * 1 . /etc/profile && restic -r ${DOL}REPO_LOCAL/pictures check --verbose >>/var/log/restic.log
    25 5 * * 1 . /etc/profile && restic -r ${DOL}REPO_LOCAL/share check --verbose >>/var/log/restic.log
    30 5 * * 1 . /etc/profile && restic -r ${DOL}REPO_LOCAL/u check --verbose >>/var/log/restic.log
    35 5 * * 1 . /etc/profile && restic -r ${DOL}REPO_LOCAL/webmail check --verbose >>/var/log/restic.log
    40 5 * * 1 . /etc/profile && restic -r ${DOL}REPO_LOCAL/home check --verbose >>/var/log/restic.log

    # Prune monthly, on the 2nd/3rd
    0 5 2 * * . /etc/profile && restic -r ${DOL}REPO_B2:misc prune >>/var/log/restic.log
    5 5 2 * * . /etc/profile && restic -r ${DOL}REPO_B2:cloud prune >>/var/log/restic.log
    10 5 2 * * . /etc/profile && restic -r ${DOL}REPO_B2:household prune >>/var/log/restic.log
    15 5 2 * * . /etc/profile && restic -r ${DOL}REPO_B2:nexus prune >>/var/log/restic.log
    20 5 2 * * . /etc/profile && . /bin/set-key.sh pictures && restic -r ${DOL}REPO_B2_PIC:pictures prune >>/var/log/restic.log
    25 5 2 * * . /etc/profile && restic -r ${DOL}REPO_B2:share prune >>/var/log/restic.log
    30 5 2 * * . /etc/profile && . /bin/set-key.sh user && restic -r ${DOL}REPO_B2_USER:u prune >>/var/log/restic.log
    35 5 2 * * . /etc/profile && . /bin/set-key.sh mail && restic -r ${DOL}REPO_B2_MAIL:webmail prune >>/var/log/restic.log
    35 5 2 * * . /etc/profile && . /bin/set-key.sh mail && restic -r ${DOL}REPO_B2_MAIL:home prune >>/var/log/restic.log
    0 5 3 * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/misc prune >>/var/log/restic.log
    5 5 3 * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/cloud prune >>/var/log/restic.log
    10 5 3 * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/household prune >>/var/log/restic.log
    15 5 3 * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/nexus prune >>/var/log/restic.log
    20 5 3 * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/pictures prune >>/var/log/restic.log
    25 5 3 * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/share prune >>/var/log/restic.log
    30 5 3 * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/u prune >>/var/log/restic.log
    35 5 3 * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/webmail prune >>/var/log/restic.log
    40 5 3 * * . /etc/profile && restic -r ${DOL}REPO_LOCAL/home prune >>/var/log/restic.log

  set-key.sh: |
    # Use this script to apply per-bucket B2 API keys
    export B2_ACCOUNT_ID=`cat ${DOL}HOME/.restic/b2-apikey/${DOL}1-id`
    export B2_ACCOUNT_KEY=`cat ${DOL}HOME/.restic/b2-apikey/${DOL}1-key`

  excludes.txt: |
    .imap
    lost+found
    MP3/dup
    nextcloud.log
    Snapshots/*.sav
